### ISSUE TITLE
new Experimental version of Timberborn crashed with Unified Factions

### ISSUE THREAD

**Issue by alerum68** [hawkfalcon/Timberborn-Mods#1]
Checked by disabling each mod, until until Unified Factions caused crashed.  Attached Timberborn generated error report.

[error-report-2021-11-24-10h17m44s.zip](https://github.com/hawkfalcon/Timberborn-Mods/files/7598053/error-report-2021-11-24-10h17m44s.zip)

**Comment by agentoranger** [comment]
Thanks for uploading this, I too saw that there was some problems after updating.

**Comment by hawkfalcon** [comment]
https://github.com/hawkfalcon/Timberborn-Mods/releases/tag/Experimental
