### ISSUE TITLE
Game Crash on Building Biofuel Tank or Biofuel Refinery (InvalidOperationException: Sequence contains no matching elements)

### ISSUE THREAD

**Issue by Mlezivan** [hawkfalcon/Timberborn-Mods#10]
![image](https://user-images.githubusercontent.com/48296623/191652238-d1c67d4e-2739-4fcd-abaf-9e0b97b8036d.png)

Let me know if you need anything else, like log files, save file, or modlist.
I will try to respond soon.

**Comment by hawkfalcon** [comment]
Log please, and what you were doing

**Comment by Mlezivan** [comment]
[error-report-2022-09-21-22h13m22s.zip](https://github.com/hawkfalcon/Timberborn-Mods/files/9622053/error-report-2022-09-21-22h13m22s.zip)
Does this work for the log?

As for what I was doing, I was just letting the game run, building a few things.
I could try to pinpoint it. Could be a Golem getting build or maybe me building a biofuel tank on top of some platforms.

**Comment by Mlezivan** [comment]
Just confirmed in another playthrough, it was building a Biofuel tank

**Comment by Mlezivan** [comment]
Just discovered, also crashes in the same way when building the Biofuel Refinery

**Comment by Mlezivan** [comment]
Just discovered, also crashes in the same way when building the Catalyst Tank

**Comment by Mlezivan** [comment]
Note that this does not affect the Charging Station or Control Tower, just the Folktails golem needs buildings.
