### ISSUE TITLE
Creative mod not working

### ISSUE THREAD

**Issue by FatalMeteor** [hawkfalcon/Timberborn-Mods#11]
Hello Hawkfalcon thanks for all your hardwork I am not sure if it is only me but creative mode is not working, map editor does works perfect, but even when I turn on the creative mode the buildings dont build instantly and still says that there arent enought science point.

**Comment by hawkfalcon** [comment]
What does the config say?

**Comment by FatalMeteor** [comment]
Hello thank you for your response, not sure where that is sorry. I am new
to timberborn modding.

**Comment by Ptasismok** [comment]
Simple thing.
Make sure you have File Viewer Plus installed and this mod is installed with Thunderstore Mod Manager.
In TMM, go to Config Editor, find BepInEx/plugins/hawkfalcon-CreativeMode/configs/CreativeModeConfig.json,
click Open File and change "DisableScienceCost" from false to true. Easy as that!

**Comment by gregspruce** [comment]
I'm experience the same issue. I've uninstalled and reinstalled the mod, checking the configs, no luck.
