### ISSUE TITLE
[Creative Mode] Not working to turn off again.

### ISSUE THREAD

**Issue by AndRo-Marian** [hawkfalcon/Timberborn-Mods#13]
After using it to build something and turning off when placing again is like the mod is still enabled for that item.
I need to restart the game to work again.

+ Make it disabled by default.

**Comment by Slemskivling** [comment]
I ran into this issue as well and came up with a solution, I thought that I might as well share it in case @hawkfalcon or anybody else is interested. I'm frankly very unfamiliar with GitHub so I won't be making any pull requests, forks or anything like that.

Anyway:
I saw that component._placeFinished is never explicitly set/reset to false in the PlaceInstantly function (inside CreativeModePlugin.cs). So even if creative mode is disabled, _placeFinished is never toggled off for the affected prefab:
```
        static bool PlaceInstantly(BlockObject prefab)
        {
            if (Enabled && config.EnableInstantBuilding)
            {
                Building component = prefab.GetComponent<Building>();
                component._placeFinished = true;
            }
            return true;
        }
```

Just adding an else statement which sets component._placeFinished to false and then rebuilding worked fine for me:
```
        static bool PlaceInstantly(BlockObject prefab)
        {
            Building component = prefab.GetComponent<Building>();
            if (Enabled && config.EnableInstantBuilding) {
                component._placeFinished = true;
            }
            else {
                component._placeFinished = false;
            }
            return true;
        }
```
