### ISSUE TITLE
Creative Mode / Experimental Branch

### ISSUE THREAD

**Issue by FozzieDNC** [hawkfalcon/Timberborn-Mods#4]
Mod stopped working on experimental after the last patch. Not sure if will affect the mod when patch goes to Retail, but I would imagine it will.

**Comment by hawkfalcon** [comment]
Thanks, I'll update soon and release when experimental is done

**Comment by FozzieDNC** [comment]
So creative mode loads as long as the Map Editing tools are disabled. otherwise it sits in limbo on loading screen when you try to load a game. Broken on release today when they patched.

Thanks for everything you do and have done!

**Comment by TheToolGuy** [comment]
When you have could you update this mod ?
This mod breaks in Experimental exiting with a failure.

(TimberAPI is at version 0.4.3, maybe that's the culprit ?)

**Comment by hawkfalcon** [comment]
Updated Creative Mode https://timberborn.thunderstore.io/package/hawkfalcon/CreativeMode/
