### ISSUE TITLE
Beaverbuffs mod is not functioning

### ISSUE THREAD

**Issue by yechingu** [hawkfalcon/Timberborn-Mods#5]
It is lacking the config fille after installation for some reason and blefinx cannot load the mod.

**Comment by thargan81** [comment]
I'm seeing a similar issue. The mod used to work, and I think it stopped after updating TimberAPI but I've not been able to find an older version that makes it work again. All I get in the loader logs that's relevant are these lines:

`[Info   :   BepInEx] Loading [Beaver Buffs 1.1.0]
[Warning: Unity Log] The script 'BeaverBuffs.BeaverBuffsPlugin' could not be instantiated!`

**Comment by hawkfalcon** [comment]
I’m looking for someone to take over this mod

**Comment by Valoneu** [comment]
i have same problem as thargan81

**Comment by kirkirik** [comment]
Has a solution been found for this issue of the config file file not appearing in thunderstore manager?

**Comment by Valoneu** [comment]
> 

the mod doesent work man ofc the config wont show up you can try WellbeingBuffs you can edit that exactly how u want
