### ISSUE TITLE
Issue Starting Timberborn from Thunderstore

### ISSUE THREAD

**Issue by rheaumep** [hawkfalcon/Timberborn-Mods#7]
Please help :)

[log.txt](https://github.com/hawkfalcon/Timberborn-Mods/files/9255570/log.txt)

**Comment by rheaumep** [comment]
Wrong document, sorry!
[LogOutput.log](https://github.com/hawkfalcon/Timberborn-Mods/files/9255577/LogOutput.log)

**Comment by orlra** [comment]
mod work priority dont work, you have singleton issue that comes from that mod, if you disable it, it should start.
